export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const RESET_PASS_STATUS_CODE = 'RESET_PASS_STATUS_CODE';

export const GET_GROUPS = 'GET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';

export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENTS = 'GET_STUDENTS';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const EDIT_STUDENT_PUT = 'EDIT_STUDENT_PUT';
export const CHANGE_IS_EDIT_FALSE = 'CHANGE_IS_EDIT_FALSE';

export const ADD_TEACHER = 'ADD_TEACHER';
export const GET_TEACHERS = 'GET_TEACHERS';
export const EDIT_TEACHER = 'EDIT_TEACHER';

export const GET_DISCIPLINE_SCHEDULE = 'GET_DISCIPLINE_SCHEDULE';
export const GET_DISCIPLINES = 'GET_DISCIPLINES';
export const ADD_DISCIPLINE = 'ADD_DISCIPLINE';
export const EDIT_DISCIPLINE = 'EDIT_DISCIPLINE';
export const GET_DISCIPLINE_MODEL_SCHEDULE = 'GET_DISCIPLINE_MODEL_SCHEDULE';
export const ADD_DISCIPLINE_MODEL_SCHEDULE = 'ADD_DISCIPLINE_MODEL_SCHEDULE';
export const EDIT_DISCIPLINE_MODEL_SCHEDULE = 'EDIT_DISCIPLINE_MODEL_SCHEDULE';

export const GET_GRADES = 'GET_GRADES';
export const ADD_GRADE = 'ADD_GRADE';

export const GET_MAJORS = 'GET_MAJORS';
export const EDIT_MAJOR = 'EDIT_MAJOR';
export const ADD_MAJOR = 'ADD_MAJOR';

export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEYS = 'GET_SURVEYS';
export const ADD_SURVEY = 'ADD_SURVEY';
export const GET_SURVEY_LOG = 'GET_SURVEY_LOG';
export const SHOW_ON_HOME = 'SHOW_ON_HOME';
